---
- name: build docker image from Dockerfile
  docker_image:
    name: nginx_logrotate
    path: docker
    state: build

- name: Run nginx_logrotate docker container
  docker_container:
    image: nginx_logrotate:latest
    path: docker
    state: running
    ports:
      - "8080:80"
